/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as InspirationSlugRouteImport } from './routes/inspiration.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as CustomPayIdRouteImport } from './routes/custom.pay.$id'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutProductsRouteImport } from './routes/admin/_layout/products'
import { Route as AdminLayoutOrdersRouteImport } from './routes/admin/_layout/orders'
import { Route as AdminLayoutGalleryRouteImport } from './routes/admin/_layout/gallery'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as AdminLayoutProductsIndexRouteImport } from './routes/admin/_layout/products.index'
import { Route as AdminLayoutOrdersIndexRouteImport } from './routes/admin/_layout/orders.index'
import { Route as CustomPayIdSuccessRouteImport } from './routes/custom.pay.$id.success'
import { Route as AdminLayoutProductsNewRouteImport } from './routes/admin/_layout/products.new'
import { Route as AdminLayoutProductsIdRouteImport } from './routes/admin/_layout/products.$id'
import { Route as AdminLayoutOrdersCustomRouteImport } from './routes/admin/_layout/orders.custom'
import { Route as AdminLayoutGalleryNewRouteImport } from './routes/admin/_layout/gallery.new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationSlugRoute = InspirationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InspirationRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const CustomPayIdRoute = CustomPayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => CustomRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProductsRoute = AdminLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersRoute = AdminLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutGalleryRoute = AdminLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProductsIndexRoute =
  AdminLayoutProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutProductsRoute,
  } as any)
const AdminLayoutOrdersIndexRoute = AdminLayoutOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutOrdersRoute,
} as any)
const CustomPayIdSuccessRoute = CustomPayIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CustomPayIdRoute,
} as any)
const AdminLayoutProductsNewRoute = AdminLayoutProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLayoutProductsRoute,
} as any)
const AdminLayoutProductsIdRoute = AdminLayoutProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLayoutProductsRoute,
} as any)
const AdminLayoutOrdersCustomRoute = AdminLayoutOrdersCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => AdminLayoutOrdersRoute,
} as any)
const AdminLayoutGalleryNewRoute = AdminLayoutGalleryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLayoutGalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRouteWithChildren
  '/inspiration': typeof InspirationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/gallery': typeof AdminLayoutGalleryRouteWithChildren
  '/admin/orders': typeof AdminLayoutOrdersRouteWithChildren
  '/admin/products': typeof AdminLayoutProductsRouteWithChildren
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/custom/pay/$id': typeof CustomPayIdRouteWithChildren
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/gallery/new': typeof AdminLayoutGalleryNewRoute
  '/admin/orders/custom': typeof AdminLayoutOrdersCustomRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/products/new': typeof AdminLayoutProductsNewRoute
  '/custom/pay/$id/success': typeof CustomPayIdSuccessRoute
  '/admin/orders/': typeof AdminLayoutOrdersIndexRoute
  '/admin/products/': typeof AdminLayoutProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRouteWithChildren
  '/inspiration': typeof InspirationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/gallery': typeof AdminLayoutGalleryRouteWithChildren
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/custom/pay/$id': typeof CustomPayIdRouteWithChildren
  '/admin/gallery/new': typeof AdminLayoutGalleryNewRoute
  '/admin/orders/custom': typeof AdminLayoutOrdersCustomRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/products/new': typeof AdminLayoutProductsNewRoute
  '/custom/pay/$id/success': typeof CustomPayIdSuccessRoute
  '/admin/orders': typeof AdminLayoutOrdersIndexRoute
  '/admin/products': typeof AdminLayoutProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRouteWithChildren
  '/inspiration': typeof InspirationRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inspiration/$slug': typeof InspirationSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/gallery': typeof AdminLayoutGalleryRouteWithChildren
  '/admin/_layout/orders': typeof AdminLayoutOrdersRouteWithChildren
  '/admin/_layout/products': typeof AdminLayoutProductsRouteWithChildren
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/custom/pay/$id': typeof CustomPayIdRouteWithChildren
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/gallery/new': typeof AdminLayoutGalleryNewRoute
  '/admin/_layout/orders/custom': typeof AdminLayoutOrdersCustomRoute
  '/admin/_layout/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/_layout/products/new': typeof AdminLayoutProductsNewRoute
  '/custom/pay/$id/success': typeof CustomPayIdSuccessRoute
  '/admin/_layout/orders/': typeof AdminLayoutOrdersIndexRoute
  '/admin/_layout/products/': typeof AdminLayoutProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/inspiration'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/checkout/success'
    | '/inspiration/$slug'
    | '/product/$slug'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/custom/pay/$id'
    | '/admin/'
    | '/admin/gallery/new'
    | '/admin/orders/custom'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/custom/pay/$id/success'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/inspiration'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/checkout/success'
    | '/inspiration/$slug'
    | '/product/$slug'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/settings'
    | '/custom/pay/$id'
    | '/admin/gallery/new'
    | '/admin/orders/custom'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/custom/pay/$id/success'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/inspiration'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/_layout'
    | '/checkout/success'
    | '/inspiration/$slug'
    | '/product/$slug'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/gallery'
    | '/admin/_layout/orders'
    | '/admin/_layout/products'
    | '/admin/_layout/settings'
    | '/custom/pay/$id'
    | '/admin/_layout/'
    | '/admin/_layout/gallery/new'
    | '/admin/_layout/orders/custom'
    | '/admin/_layout/products/$id'
    | '/admin/_layout/products/new'
    | '/custom/pay/$id/success'
    | '/admin/_layout/orders/'
    | '/admin/_layout/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRouteWithChildren
  InspirationRoute: typeof InspirationRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/$slug': {
      id: '/inspiration/$slug'
      path: '/$slug'
      fullPath: '/inspiration/$slug'
      preLoaderRoute: typeof InspirationSlugRouteImport
      parentRoute: typeof InspirationRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/custom/pay/$id': {
      id: '/custom/pay/$id'
      path: '/pay/$id'
      fullPath: '/custom/pay/$id'
      preLoaderRoute: typeof CustomPayIdRouteImport
      parentRoute: typeof CustomRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products': {
      id: '/admin/_layout/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminLayoutProductsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders': {
      id: '/admin/_layout/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminLayoutOrdersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/gallery': {
      id: '/admin/_layout/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminLayoutGalleryRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products/': {
      id: '/admin/_layout/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminLayoutProductsIndexRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
    '/admin/_layout/orders/': {
      id: '/admin/_layout/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminLayoutOrdersIndexRouteImport
      parentRoute: typeof AdminLayoutOrdersRoute
    }
    '/custom/pay/$id/success': {
      id: '/custom/pay/$id/success'
      path: '/success'
      fullPath: '/custom/pay/$id/success'
      preLoaderRoute: typeof CustomPayIdSuccessRouteImport
      parentRoute: typeof CustomPayIdRoute
    }
    '/admin/_layout/products/new': {
      id: '/admin/_layout/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminLayoutProductsNewRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
    '/admin/_layout/products/$id': {
      id: '/admin/_layout/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminLayoutProductsIdRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
    '/admin/_layout/orders/custom': {
      id: '/admin/_layout/orders/custom'
      path: '/custom'
      fullPath: '/admin/orders/custom'
      preLoaderRoute: typeof AdminLayoutOrdersCustomRouteImport
      parentRoute: typeof AdminLayoutOrdersRoute
    }
    '/admin/_layout/gallery/new': {
      id: '/admin/_layout/gallery/new'
      path: '/new'
      fullPath: '/admin/gallery/new'
      preLoaderRoute: typeof AdminLayoutGalleryNewRouteImport
      parentRoute: typeof AdminLayoutGalleryRoute
    }
  }
}

interface AdminLayoutGalleryRouteChildren {
  AdminLayoutGalleryNewRoute: typeof AdminLayoutGalleryNewRoute
}

const AdminLayoutGalleryRouteChildren: AdminLayoutGalleryRouteChildren = {
  AdminLayoutGalleryNewRoute: AdminLayoutGalleryNewRoute,
}

const AdminLayoutGalleryRouteWithChildren =
  AdminLayoutGalleryRoute._addFileChildren(AdminLayoutGalleryRouteChildren)

interface AdminLayoutOrdersRouteChildren {
  AdminLayoutOrdersCustomRoute: typeof AdminLayoutOrdersCustomRoute
  AdminLayoutOrdersIndexRoute: typeof AdminLayoutOrdersIndexRoute
}

const AdminLayoutOrdersRouteChildren: AdminLayoutOrdersRouteChildren = {
  AdminLayoutOrdersCustomRoute: AdminLayoutOrdersCustomRoute,
  AdminLayoutOrdersIndexRoute: AdminLayoutOrdersIndexRoute,
}

const AdminLayoutOrdersRouteWithChildren =
  AdminLayoutOrdersRoute._addFileChildren(AdminLayoutOrdersRouteChildren)

interface AdminLayoutProductsRouteChildren {
  AdminLayoutProductsIdRoute: typeof AdminLayoutProductsIdRoute
  AdminLayoutProductsNewRoute: typeof AdminLayoutProductsNewRoute
  AdminLayoutProductsIndexRoute: typeof AdminLayoutProductsIndexRoute
}

const AdminLayoutProductsRouteChildren: AdminLayoutProductsRouteChildren = {
  AdminLayoutProductsIdRoute: AdminLayoutProductsIdRoute,
  AdminLayoutProductsNewRoute: AdminLayoutProductsNewRoute,
  AdminLayoutProductsIndexRoute: AdminLayoutProductsIndexRoute,
}

const AdminLayoutProductsRouteWithChildren =
  AdminLayoutProductsRoute._addFileChildren(AdminLayoutProductsRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutGalleryRoute: typeof AdminLayoutGalleryRouteWithChildren
  AdminLayoutOrdersRoute: typeof AdminLayoutOrdersRouteWithChildren
  AdminLayoutProductsRoute: typeof AdminLayoutProductsRouteWithChildren
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutGalleryRoute: AdminLayoutGalleryRouteWithChildren,
  AdminLayoutOrdersRoute: AdminLayoutOrdersRouteWithChildren,
  AdminLayoutProductsRoute: AdminLayoutProductsRouteWithChildren,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CustomPayIdRouteChildren {
  CustomPayIdSuccessRoute: typeof CustomPayIdSuccessRoute
}

const CustomPayIdRouteChildren: CustomPayIdRouteChildren = {
  CustomPayIdSuccessRoute: CustomPayIdSuccessRoute,
}

const CustomPayIdRouteWithChildren = CustomPayIdRoute._addFileChildren(
  CustomPayIdRouteChildren,
)

interface CustomRouteChildren {
  CustomPayIdRoute: typeof CustomPayIdRouteWithChildren
}

const CustomRouteChildren: CustomRouteChildren = {
  CustomPayIdRoute: CustomPayIdRouteWithChildren,
}

const CustomRouteWithChildren =
  CustomRoute._addFileChildren(CustomRouteChildren)

interface InspirationRouteChildren {
  InspirationSlugRoute: typeof InspirationSlugRoute
}

const InspirationRouteChildren: InspirationRouteChildren = {
  InspirationSlugRoute: InspirationSlugRoute,
}

const InspirationRouteWithChildren = InspirationRoute._addFileChildren(
  InspirationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRouteWithChildren,
  InspirationRoute: InspirationRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
