/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutSubscribersRouteImport } from './routes/admin/_layout/subscribers'
import { Route as AdminLayoutProductsRouteImport } from './routes/admin/_layout/products'
import { Route as AdminLayoutOrdersRouteImport } from './routes/admin/_layout/orders'
import { Route as AdminLayoutCustomRequestsRouteImport } from './routes/admin/_layout/custom-requests'
import { Route as AdminLayoutProductsIndexRouteImport } from './routes/admin/_layout/products.index'
import { Route as AdminLayoutProductsNewRouteImport } from './routes/admin/_layout/products.new'
import { Route as AdminLayoutProductsIdRouteImport } from './routes/admin/_layout/products.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSubscribersRoute = AdminLayoutSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProductsRoute = AdminLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersRoute = AdminLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCustomRequestsRoute =
  AdminLayoutCustomRequestsRouteImport.update({
    id: '/custom-requests',
    path: '/custom-requests',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProductsIndexRoute =
  AdminLayoutProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutProductsRoute,
  } as any)
const AdminLayoutProductsNewRoute = AdminLayoutProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLayoutProductsRoute,
} as any)
const AdminLayoutProductsIdRoute = AdminLayoutProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLayoutProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/custom-requests': typeof AdminLayoutCustomRequestsRoute
  '/admin/orders': typeof AdminLayoutOrdersRoute
  '/admin/products': typeof AdminLayoutProductsRouteWithChildren
  '/admin/subscribers': typeof AdminLayoutSubscribersRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/products/new': typeof AdminLayoutProductsNewRoute
  '/admin/products/': typeof AdminLayoutProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/custom-requests': typeof AdminLayoutCustomRequestsRoute
  '/admin/orders': typeof AdminLayoutOrdersRoute
  '/admin/subscribers': typeof AdminLayoutSubscribersRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/products/new': typeof AdminLayoutProductsNewRoute
  '/admin/products': typeof AdminLayoutProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/custom': typeof CustomRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/_layout/custom-requests': typeof AdminLayoutCustomRequestsRoute
  '/admin/_layout/orders': typeof AdminLayoutOrdersRoute
  '/admin/_layout/products': typeof AdminLayoutProductsRouteWithChildren
  '/admin/_layout/subscribers': typeof AdminLayoutSubscribersRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/_layout/products/new': typeof AdminLayoutProductsNewRoute
  '/admin/_layout/products/': typeof AdminLayoutProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/product/$slug'
    | '/admin/custom-requests'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/subscribers'
    | '/admin/'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/product/$slug'
    | '/admin/custom-requests'
    | '/admin/orders'
    | '/admin/subscribers'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/admin/_layout'
    | '/admin/login'
    | '/product/$slug'
    | '/admin/_layout/custom-requests'
    | '/admin/_layout/orders'
    | '/admin/_layout/products'
    | '/admin/_layout/subscribers'
    | '/admin/_layout/'
    | '/admin/_layout/products/$id'
    | '/admin/_layout/products/new'
    | '/admin/_layout/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomRoute: typeof CustomRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/subscribers': {
      id: '/admin/_layout/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminLayoutSubscribersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products': {
      id: '/admin/_layout/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminLayoutProductsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders': {
      id: '/admin/_layout/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminLayoutOrdersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/custom-requests': {
      id: '/admin/_layout/custom-requests'
      path: '/custom-requests'
      fullPath: '/admin/custom-requests'
      preLoaderRoute: typeof AdminLayoutCustomRequestsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products/': {
      id: '/admin/_layout/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminLayoutProductsIndexRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
    '/admin/_layout/products/new': {
      id: '/admin/_layout/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminLayoutProductsNewRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
    '/admin/_layout/products/$id': {
      id: '/admin/_layout/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminLayoutProductsIdRouteImport
      parentRoute: typeof AdminLayoutProductsRoute
    }
  }
}

interface AdminLayoutProductsRouteChildren {
  AdminLayoutProductsIdRoute: typeof AdminLayoutProductsIdRoute
  AdminLayoutProductsNewRoute: typeof AdminLayoutProductsNewRoute
  AdminLayoutProductsIndexRoute: typeof AdminLayoutProductsIndexRoute
}

const AdminLayoutProductsRouteChildren: AdminLayoutProductsRouteChildren = {
  AdminLayoutProductsIdRoute: AdminLayoutProductsIdRoute,
  AdminLayoutProductsNewRoute: AdminLayoutProductsNewRoute,
  AdminLayoutProductsIndexRoute: AdminLayoutProductsIndexRoute,
}

const AdminLayoutProductsRouteWithChildren =
  AdminLayoutProductsRoute._addFileChildren(AdminLayoutProductsRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutCustomRequestsRoute: typeof AdminLayoutCustomRequestsRoute
  AdminLayoutOrdersRoute: typeof AdminLayoutOrdersRoute
  AdminLayoutProductsRoute: typeof AdminLayoutProductsRouteWithChildren
  AdminLayoutSubscribersRoute: typeof AdminLayoutSubscribersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutCustomRequestsRoute: AdminLayoutCustomRequestsRoute,
  AdminLayoutOrdersRoute: AdminLayoutOrdersRoute,
  AdminLayoutProductsRoute: AdminLayoutProductsRouteWithChildren,
  AdminLayoutSubscribersRoute: AdminLayoutSubscribersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomRoute: CustomRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
