-- Restore the pre-import curated shop catalog.
--
-- The previous real-catalog seed imported products from the old website. This
-- migration removes those imported rows from any database where that seed has
-- already been applied, then upserts the curated revamp starter products.

delete from public.products
where category in (
  'Embroidery Apparel',
  'Embroidery Home & Accessories',
  'Engraved Drinkware',
  'Engraved Accessories',
  'Gift Sets & Stationery'
)
or slug in (
  'yahweh-christian-sweatshirt',
  'of-course-i-talk-to-god-tee',
  'we-still-do-anniversary-tee',
  'yahweh-faith-tee',
  'personalized-vintage-tee',
  'faith-over-fear-tee',
  'mr-mrs-embroidered-tee',
  'embroidered-towel-bathrobe',
  'cant-steal-my-joy-sweatshirt',
  'mommy-est-legacy-tee',
  'minky-blanket-custom-name',
  'sweet-16-throw-pillow',
  'mr-mrs-throw-pillow',
  'repeated-name-throw-pillow',
  'vintage-birthday-throw-pillow',
  'tote-bag-name-design',
  'photo-tote-bag',
  'mr-mrs-tote-wedding-favor',
  'mr-mrs-15oz-mug',
  'wedding-mug-couples',
  'photo-coffee-mug',
  'stainless-tumbler-20oz',
  'photo-coffee-mug-11oz',
  'monogram-initial-mug',
  'love-yourself-tumbler',
  'god-is-our-refuge-tumbler',
  'gold-affirmations-tumbler',
  'photo-tumbler',
  'floral-name-mug',
  'leather-circle-keychain',
  'photo-keychain',
  'leather-heart-keychain',
  'leather-keychain',
  'wristlet-keychain',
  'ballpoint-pens',
  'leather-travel-wallet',
  'crystal-photo-frame',
  'year-of-affirmations-journal',
  'monthly-planner-2026',
  'praise-prayer-journal',
  'personalize-gift-set',
  'party-favor-bags',
  'jumbo-lollipop-favors',
  'custom-round-stickers'
);

insert into public.products
  (slug, name, description, price, category, images, customizable, best_seller, in_stock, featured, sizes, occasions)
values
  (
    'faith-over-fear-sweatshirt',
    'Faith Over Fear Sweatshirt',
    'A cozy heavyweight sweatshirt embroidered with our signature Faith Over Fear script. Made from a soft cotton-poly blend and finished by hand in our studio.',
    48,
    'Faith Apparel',
    array['local:p1', 'local:cat-faith'],
    true,
    true,
    true,
    true,
    array['XS','S','M','L','XL'],
    array['Encouragement','Birthday','Ministry']
  ),
  (
    'blessed-mom-mug',
    'Blessed Mom 15oz Mug',
    'A premium 15oz ceramic mug personalized with a delicate script. Dishwasher-safe and gift-ready.',
    22,
    'Mugs & Tumblers',
    array['local:p2', 'local:cat-mugs'],
    true,
    true,
    true,
    true,
    null,
    array['Mother''s Day','Birthday','Thank You']
  ),
  (
    'grateful-canvas-tote',
    'Grateful Canvas Tote',
    'A structured heavyweight canvas tote embroidered with Grateful. Roomy enough for everyday carry and refined enough for weekends away.',
    28,
    'Accessories',
    array['local:p3', 'local:cat-accessories'],
    true,
    false,
    true,
    false,
    null,
    array['Thank You','Everyday','Teacher Gift']
  ),
  (
    'signature-navy-gift-box',
    'Signature Navy Gift Box',
    'A curated set with an embroidered apparel piece, signature mug, and scripture card presented in our navy box with gold ribbon.',
    85,
    'Gift Sets',
    array['local:p4', 'local:cat-gifts'],
    false,
    true,
    true,
    true,
    null,
    array['Corporate','Ministry','Milestone']
  ),
  (
    'walk-by-faith-hoodie',
    'Walk by Faith Hoodie',
    'An oversized hoodie in warm cream with embroidered Walk by Faith detailing. Brushed fleece interior for everyday softness.',
    54,
    'Faith Apparel',
    array['local:cat-faith', 'local:p1'],
    true,
    false,
    true,
    false,
    array['S','M','L','XL'],
    array['Encouragement','Ministry','Birthday']
  ),
  (
    'custom-name-mug',
    'Custom Name Coffee Mug',
    'Personalize with any name in a refined script. A thoughtful, everyday gift for the coffee lover in your life.',
    24,
    'Mugs & Tumblers',
    array['local:cat-mugs', 'local:p2'],
    true,
    false,
    true,
    false,
    null,
    array['Birthday','Thank You','Teacher Gift']
  ),
  (
    'embroidered-day-tote',
    'Embroidered Day Tote',
    'A refined everyday tote with monogram embroidery of your choice. Finished with sturdy handles and an interior pocket.',
    32,
    'Accessories',
    array['local:cat-accessories', 'local:p3'],
    true,
    false,
    true,
    false,
    null,
    array['Everyday','Teacher Gift','Corporate']
  ),
  (
    'mothers-day-box',
    'Mother''s Day Curated Box',
    'A limited edition set for Mom: personalized mug, silk-touch scarf, candle, and a heartfelt scripture card.',
    95,
    'Gift Sets',
    array['local:cat-gifts', 'local:p4'],
    true,
    false,
    true,
    false,
    null,
    array['Mother''s Day','Birthday','Milestone']
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  images = excluded.images,
  customizable = excluded.customizable,
  best_seller = excluded.best_seller,
  in_stock = excluded.in_stock,
  featured = excluded.featured,
  sizes = excluded.sizes,
  occasions = excluded.occasions,
  updated_at = now();
