-- Real product catalog, extracted from the client's live store
-- (www.btcollectionllc.com), replacing the placeholder demo products that
-- shipped with this rebuild. Images are self-hosted copies in the
-- `product-images` bucket (see previous migration), not hotlinked from the
-- live store.
--
-- Categories match src/lib/categories.ts exactly — keep both in sync.

insert into public.products
  (slug, name, description, price, category, images, customizable, best_seller, in_stock, featured, sizes, occasions)
values
  -- Embroidery Apparel
  ('yahweh-christian-sweatshirt', 'Yahweh Christian Sweatshirt', 'A faith-based scripture pullover, hand-embroidered with care.', 29.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/yahweh-christian-sweatshirt.png'], true, true, true, false, array['S','M','L','XL','2XL'], array['Encouragement','Ministry']),
  ('of-course-i-talk-to-god-tee', 'Of Course I Talk To God Unisex T-Shirt', 'A bold faith statement tee, embroidered to order.', 19.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/of-course-i-talk-to-god-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Ministry']),
  ('we-still-do-anniversary-tee', 'We Still Do Anniversary Couples T-Shirt', 'A custom couples tee for anniversaries and vow renewals.', 19.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/we-still-do-anniversary-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Anniversary','Wedding']),
  ('yahweh-faith-tee', 'Yahweh Christian Faith T-Shirt', 'An inspirational bible-verse tee, embroidered by hand.', 24.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/yahweh-faith-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Ministry']),
  ('personalized-vintage-tee', 'Personalized Vintage Unisex T-Shirt', 'A retro-style comfort tee, personalized with your name or phrase.', 24.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/personalized-vintage-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Birthday']),
  ('faith-over-fear-tee', 'Faith Over Fear Christian T-Shirt', 'An inspirational scripture tee, our signature Faith Over Fear script.', 34.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/faith-over-fear-tee.png'], true, true, true, true, array['S','M','L','XL','2XL'], array['Encouragement','Ministry','Birthday']),
  ('mr-mrs-embroidered-tee', 'Personalized Mr & Mrs Embroidered T-Shirt', 'A matching couples tee, embroidered with your names.', 19.99, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/mr-mrs-embroidered-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Wedding','Anniversary']),
  ('embroidered-towel-bathrobe', 'Personalized Embroidered Towel & Bathrobe', 'A hand-embroidered towel and bathrobe set, monogrammed for gifting.', 90.00, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/embroidered-towel-bathrobe.png'], true, false, true, false, null, array['Wedding','Baby']),
  ('cant-steal-my-joy-sweatshirt', 'Can''t Steal My Joy Christian Women''s Sweatshirt', 'A cozy faith-inspired sweatshirt for everyday encouragement.', 45.00, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/cant-steal-my-joy-sweatshirt.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Encouragement']),
  ('mommy-est-legacy-tee', 'Mommy EST (Year) Legacy Women''s T-Shirt', 'A personalized keepsake tee marking the year motherhood began.', 35.00, 'Embroidery Apparel', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/mommy-est-legacy-tee.png'], true, false, true, false, array['S','M','L','XL','2XL'], array['Baby','Mother''s Day']),

  -- Embroidery Home & Accessories
  ('minky-blanket-custom-name', 'Minky Blanket with Custom Name', 'A soft minky blanket embroidered with baby''s name — a treasured baby-shower gift.', 30.00, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/minky-blanket-custom-name.png'], true, false, true, true, null, array['Baby']),
  ('sweet-16-throw-pillow', 'Personalized Sweet 16 Throw Pillow', 'A photo throw pillow celebrating a milestone birthday.', 50.00, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/sweet-16-throw-pillow.png'], true, false, true, false, null, array['Birthday']),
  ('mr-mrs-throw-pillow', 'Mr. & Mrs. Personalized Name Throw Pillow', 'A custom couples-name throw pillow for the home.', 39.99, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/mr-mrs-throw-pillow.png'], true, false, true, false, null, array['Wedding','Anniversary']),
  ('repeated-name-throw-pillow', 'Personalized Repeated Name Throw Pillow', 'An 18x18in pillow with your custom name pattern repeated edge to edge.', 39.99, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/repeated-name-throw-pillow.png'], true, false, true, false, null, array['Birthday']),
  ('vintage-birthday-throw-pillow', 'Personalized Vintage Birthday Throw Pillow', 'A retro-style birthday throw pillow, personalized with name and age.', 39.00, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/vintage-birthday-throw-pillow.png'], true, false, true, false, null, array['Birthday']),
  ('tote-bag-name-design', 'Personalized Tote Bag with Name or Design', 'A structured canvas tote, personalized with a name or design of your choice.', 14.99, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-tote-bag.png'], true, false, true, false, null, array['Everyday','Teacher Appreciation']),
  ('photo-tote-bag', 'Personalized Photo Tote Bag', 'A canvas tote printed with your favorite photo.', 44.99, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-tote-bag.png'], true, false, true, false, null, array['Birthday','Mother''s Day']),
  ('mr-mrs-tote-wedding-favor', 'Mr. & Mrs. Name Tote Wedding Favors', 'Affordable custom-name totes, perfect for wedding party favors.', 9.99, 'Embroidery Home & Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/mr-mrs-tote-wedding-favor.png'], true, false, true, false, null, array['Wedding','Corporate']),

  -- Engraved Drinkware
  ('mr-mrs-15oz-mug', 'Trendy Personalized Mr. & Mrs. 15oz Mug', 'A premium 15oz ceramic mug, engraved for the happy couple.', 17.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/mr-mrs-15oz-mug.png'], true, true, true, false, null, array['Wedding','Anniversary']),
  ('wedding-mug-couples', 'Personalized Wedding Mug For Couples', 'A custom wedding mug set, engraved with your names and date.', 12.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/wedding-mug-couples.png'], true, false, true, false, null, array['Wedding']),
  ('photo-coffee-mug', 'Personalized Photo Coffee Mug', 'A custom birthday gift mug, printed with your picture and name.', 9.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-coffee-mug.png'], true, false, true, false, null, array['Birthday','Thank You']),
  ('stainless-tumbler-20oz', 'Personalized 20oz Stainless Steel Tumbler', 'A double-wall stainless tumbler with your custom name and design.', 15.00, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/stainless-tumbler-20oz.png'], true, true, true, true, null, array['Birthday','Corporate']),
  ('photo-coffee-mug-11oz', 'Personalized 11oz Photo Coffee Mug', 'An everyday 11oz mug, printed with your favorite photo.', 9.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-coffee-mug-11oz.png'], true, false, true, false, null, array['Birthday','Thank You']),
  ('monogram-initial-mug', 'Monogram Initial Name Mug', 'A 15oz personalized coffee mug with your monogram initial.', 14.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/monogram-initial-mug.png'], true, false, true, false, null, array['Birthday','Thank You']),
  ('love-yourself-tumbler', 'Love Yourself Motivational 20oz Tumbler', 'A daily-affirmation skinny tumbler to keep you motivated.', 18.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/love-yourself-tumbler.png'], false, false, true, false, null, array['Encouragement']),
  ('god-is-our-refuge-tumbler', 'God is Our Refuge 20oz Skinny Tumbler', 'A faith-inspired skinny tumbler for daily encouragement.', 18.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/god-is-our-refuge-tumbler.png'], false, false, true, false, null, array['Ministry','Encouragement']),
  ('gold-affirmations-tumbler', 'Gold Positive Affirmations 20oz Skinny Tumbler', 'A gold-foil affirmations tumbler for everyday inspiration.', 18.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/gold-affirmations-tumbler.png'], false, false, true, false, null, array['Encouragement']),
  ('photo-tumbler', 'Personalized Photo Tumbler', 'A custom picture travel cup, printed with your favorite photo.', 18.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-tumbler.png'], true, false, true, false, null, array['Birthday']),
  ('floral-name-mug', 'Floral Personalized Name Coffee Mug', 'A floral custom-name mug, a thoughtful gift for her.', 9.99, 'Engraved Drinkware', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/floral-name-mug.png'], true, false, true, false, null, array['Mother''s Day','Birthday']),

  -- Engraved Accessories
  ('leather-circle-keychain', 'Custom Leather Circle Keychain', 'A unique engraved leather circle keychain.', 4.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/leather-circle-keychain.png'], true, false, true, false, null, array['Birthday','Thank You']),
  ('photo-keychain', 'Personalized Photo Keychain', 'A custom key holder printed with your photo.', 5.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/photo-keychain.png'], true, false, true, false, null, array['Birthday']),
  ('leather-heart-keychain', 'Custom Leather Heart Keychain', 'A heart-shaped engraved leather keychain, a unique gift for loved ones.', 4.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/leather-heart-keychain.png'], true, false, true, false, null, array['Anniversary','Wedding']),
  ('leather-keychain', 'Custom Leather Keychain', 'A classic engraved leather keychain.', 4.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/leather-keychain.png'], true, true, true, false, null, array['Wedding','Corporate']),
  ('wristlet-keychain', 'Custom Wristlet Keychain', 'A personalized name wristlet keychain.', 9.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/wristlet-keychain.png'], true, false, true, false, null, array['Birthday']),
  ('ballpoint-pens', 'Customized Ballpoint Pens', 'Laser-engraved ballpoint pens, personalized with a name or message.', 24.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/ballpoint-pens.png'], true, false, true, false, null, array['Corporate','Graduation']),
  ('leather-travel-wallet', 'Personalized Hot Stamp Leather Travel Wallet', 'A leather travel wallet with hot-stamped name or initials.', 12.99, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/leather-travel-wallet.png'], true, false, true, false, null, array['Graduation','Corporate']),
  ('crystal-photo-frame', 'Personalized Crystal Photo Frame with LED Base', 'A crystal photo frame with a colorful LED light base.', 50.00, 'Engraved Accessories', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/crystal-photo-frame.jpg'], true, false, true, false, null, array['Anniversary','Wedding']),

  -- Gift Sets & Stationery
  ('year-of-affirmations-journal', 'A Year of Affirmations Journal', 'A guided daily-reflection journal, a year of affirmations.', 24.99, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/year-of-affirmations-journal.png'], false, false, true, false, null, array['Encouragement']),
  ('monthly-planner-2026', '2026 Monthly Planner', 'A monthly planner to keep the year organized with intention.', 19.99, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/monthly-planner-2026.png'], false, false, true, false, null, null),
  ('praise-prayer-journal', 'Praise & Prayer Journal', 'A faith-filled daily-reflection journal for praise and prayer.', 24.99, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/praise-prayer-journal.png'], false, false, true, false, null, array['Ministry']),
  ('personalize-gift-set', 'Personalize Gift Set', 'A curated, personalized gift set for any occasion.', 45.00, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/personalize-gift-set.png'], true, true, true, true, null, array['Birthday','Corporate','Thank You']),
  ('party-favor-bags', 'Personalized Party Favor Bags (Set of 10)', 'Candy and treat bags with printable custom labels, set of 10.', 30.00, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/party-favor-bags.png'], true, false, true, false, null, array['Birthday']),
  ('jumbo-lollipop-favors', 'Personalized Jumbo Rainbow Lollipop (Set of 12)', 'Custom candy party favors with individual labels, set of 12.', 69.99, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/jumbo-lollipop-favors.png'], true, false, true, false, null, array['Birthday']),
  ('custom-round-stickers', 'Custom Round Stickers', 'Personalized labels for gifts and events.', 8.99, 'Gift Sets & Stationery', array['https://yyrvzifopcvyzwyjwuln.supabase.co/storage/v1/object/public/product-images/custom-round-stickers.png'], true, false, true, false, null, array['Birthday','Corporate'])
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  images = excluded.images,
  customizable = excluded.customizable,
  best_seller = excluded.best_seller,
  in_stock = excluded.in_stock,
  featured = excluded.featured,
  sizes = excluded.sizes,
  occasions = excluded.occasions;
